version: '3.7'
name: wks-platform
services:
    minio:
        image: quay.io/minio/minio
        command: server /data --console-address ":9090"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        ports:
            - 9000:9000
            - 9090:9090
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        volumes:
            - minio:/data:rw

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        healthcheck:
            test: mongosh --eval 'db.stats().ok' --quiet
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        volumes:
            - mongo:/data/db:rw

    opa:
        image: openpolicyagent/opa:edge-static
        ports:
            - 8181:8181        
        command:
            - run
            - --server
            - /etc/rules/wks_policy_rules.rego
        volumes:
            - ./opa:/etc/rules:ro

    camunda:
        image: camunda/camunda-bpm-platform:run-7.20.0
        command: ./camunda.sh --rest --webapps
        ports:
            - 8080:8080
        healthcheck:
            test: curl --fail http://localhost:8080/engine-rest/version || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            mongodb:
                condition: service_healthy

    keycloak:
        image: quay.io/keycloak/keycloak:20.0.3
        command: start-dev
        environment:
            KC_HEALTH_ENABLED: "true"
            KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        healthcheck:
            test: curl --fail http://localhost:8080/health/ready || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        ports:
            - 8082:8080
        volumes:
            - keycloak:/opt/keycloak/data/

    case-engine-rest-api:
        build:
            context: apps/java/services/case-engine-rest-api
        ports:
            - 8081:8081
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_BASE_URL=${CAMUNDA_BASE_URL}
            - MONGO_DATABASE=${MONGO_WKS_DATABASE}
            - MONGO_CONN=${MONGO_CONNECTION_URL}
            - KEYCLOAK_URL=${KEYCLOAK_URL}
            - OPA_URL=${OPA_URL}
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy

    bpm-engine-c7-external-service:
        build:
            context: apps/java/services/bpm-engine-c7-external-service
        links:
            - camunda
            - case-engine-rest-api
        environment:
            - CAMUNDA_BASE_URL=${CAMUNDA_BASE_URL}
            - CAMUNDA_USERNAME=${CAMUNDA_USERNAME}
            - CAMUNDA_PASSWORD=${CAMUNDA_PASSWORD}
            - KEYCLOAK_URL=${KEYCLOAK_TOKEN_URL}
            - WKS_CASE_API_URL=${WKS_CASE_API_URL}
            - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
        depends_on:
            camunda:
                condition: service_healthy

    storage-api:
        build:
            context: apps/java/services/storage-api
        ports:
            - 8085:8085
        links:
            - minio
        environment:
            - OPA_URL=${OPA_URL}
            - KEYCLOAK_URL=${KEYCLOAK_URL}
            - MINIO_HOST=minio
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        depends_on:
            minio:
                condition: service_healthy

volumes:
    mongo:
        driver: local
    minio:
        driver: local
    keycloak:
        driver: local                