version: '3.7'
services:
    traefik:
        profiles:
            - servers
        image: traefik:v2.8
        command:
            - --log.level=debug
            - --api.insecure=true
            - --api.dashboard=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.docker=true
            - --experimental.hub=true
            - --providers.docker.exposedbydefault=false
            - --serversTransport.insecureSkipVerify=true
            - --providers.file.watch=true
            - --providers.file.directory=/traefik
        ports:
            - 80:80
            - 443:443
            - 8888:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./configs/traefik:/traefik:ro

    minio:
        image: quay.io/minio/minio
        command: server /data --console-address ":9090"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        ports:
            - 9000:9000
            - 9090:9090
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=#minio00#
        volumes:
            - minio:/data:rw

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        healthcheck:
            test: mongosh --eval 'db.stats().ok' --quiet
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        volumes:
            - mongo:/data/db:rw

    opa:
        image: openpolicyagent/opa:edge-static
        ports:
            - 8181:8181
        command:
            - run
            - --server
            - /etc/rules/wks_policy_rules.rego
        volumes:
            - ./opa:/etc/rules:ro

    camunda:
        image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:run-7.20.0
        command: ./camunda.sh --rest --webapps
        ports:
            - 8080:8080
        healthcheck:
            test: curl --fail http://localhost:8080/engine-rest/version || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        depends_on:
            mongodb:
                condition: service_healthy

    keycloak:
        image: quay.io/keycloak/keycloak:20.0.3
        command: start-dev
        environment:
            KC_HEALTH_ENABLED: "true"
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        healthcheck:
            test: curl --fail http://localhost:8080/health/ready || exit 1
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 10s
        ports:
            - 8082:8080
        volumes:
            - keycloak:/opt/keycloak/data/

    elasticsearch:
        # https://hub.docker.com/_/elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
        container_name: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - xpack.security.enabled=false
            # allow running with low disk space
            - cluster.routing.allocation.disk.threshold_enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        restart: always
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -f http://localhost:9200/_cat/health | grep -q green"
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        volumes:
            - elastic:/usr/share/elasticsearch/data

    optimize:
        image: camunda/optimize:3.9.4
        container_name: optimize
        ports:
            - "8090:8090"
        environment:
            - JAVA_OPTS=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m
            - OPTIMIZE_CAMUNDABPM_REST_URL=http://camunda:8080/engine-rest
            - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
            - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9200
            - OPTIMIZE_EVENT_INGESTION_ACCESS_TOKEN=secret        
        volumes:
            - ".configs/optimize/environment-config.yaml:/optimize/config/environment-config.yaml"
            - ".configs/optimize/OptimizeLicense.txt:/optimize/config/OptimizeLicense.txt"
            - ".configs/optimize/logo/wks_icon.svg:/optimize/config/logo/wks_icon.svg"
        restart: on-failure
        links:
            - elasticsearch
            - camunda
        depends_on:
            - elasticsearch

    case-engine-rest-api:
        build:
            context: apps/java/services/case-engine-rest-api
        ports:
            - 8081:8081
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_BASE_URL=http://camunda:8080/engine-rest
            - MONGO_DATABASE=wks
            - MONGO_CONN=mongodb://mongodb
            - KEYCLOAK_URL=http://keycloak:8080
            - OPA_URL=http://opa:8181/v1/data/wks/authz/allow
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy

    bpm-engine-c7-external-service:
        build:
            context: apps/java/services/bpm-engine-c7-external-service
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_BASE_URL=http://camunda:8080/engine-rest
            - CAMUNDA_USERNAME=demo
            - CAMUNDA_PASSWORD=demo
            - MONGO_DATABASE=wks
            - MONGO_CONN=mongodb://mongodb
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy

    email-to-case:
        build:
            context: apps/java/services/email-to-case
        ports:
            - 8083:8083
        links:
            - mongodb
            - camunda
        environment:
            - CAMUNDA_BASE_URL=http://camunda:8080/engine-rest
            - MONGO_DATABASE=wks
            - MONGO_CONN=mongodb://mongodb
            - EMAIL_CASE_PATTERN_NEW=new-case
            - EMAIL_CASE_PATTERN_UPDATE=update-case
            - KEYCLOAK_URL=http://keycloak:8080
            - OPA_URL=http://opa:8181/v1/data/wks/authz/allow
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy

    storage-api:
        build:
            context: apps/java/services/storage-api
        ports:
            - 8085:8085
        links:
            - minio
        environment:
            - OPA_URL=http://opa:8181/v1/data/wks/authz/allow
            - KEYCLOAK_URL=http://keycloak:8080
            - MINIO_HOST=minio
        depends_on:
            minio:
                condition: service_healthy

    case-portal:
        build:
            context: apps/react/case-portal
            args:
                REACT_APP_KEYCLOAK_URL: http://localhost:8082
                REACT_APP_API_URL: http://localhost:8081
                REACT_APP_EMAIL_URL: http://localhost:8083
                REACT_APP_STORAGE_URL: http://localhost:8085
        ports:
            - 3001:3000

    demo-data-loader:
        build:
            context: apps/java/services/demo-data-loader
        environment:
            - CAMUNDA_URL=http://camunda:8080/engine-rest
            - MONGO_DATABASE=localhost
            - MONGO_CONN=mongodb://mongodb
            - KEYCLOAK_URL=http://keycloak:8080
        links:
            - mongodb
            - camunda
            - keycloak
        depends_on:
            mongodb:
                condition: service_healthy
            camunda:
                condition: service_healthy
            keycloak:
                condition: service_healthy              

volumes:
    mongo:
        driver: local
    minio:
        driver: local
    keycloak:
        driver: local
    elastic:
        driver: local