server:
   port: 8081

logging:
   level:
      root: INFO
      com.wks: INFO
      com.wks.api.security: INFO
      com.wks.caseengine: INFO
      com.wks.caseengine.command: INFO
      com.wks.caseengine.pagination: INFO
      org.springframework.web.client.RestTemplate: INFO
      org.springframework.security: INFO
      org.apache.http: INFO
      httpclient.wire: INFO
      
spring.mvc.converters.preferred-json-mapper: gson

camunda.bpm.client.base-url: http://localhost:8080/engine-rest

zeebe.client.broker.gateway-address: 127.0.0.1:26500
zeebe.client.security.plaintext: true
camunda.operate.client.enabled: true
camunda.operate.client.url: http://localhost:8281
camunda.operate.client.username: demo
camunda.operate.client.password: demo

camunda.tasklist.client.url: http://localhost:8182
camunda.tasklist.client.username: demo
camunda.tasklist.client.password: demo

spring.data.mongodb.uri: ${MONGO_CONN:mongodb://localhost}
spring.data.mongodb.database: ${MONGO_DATABASE:shared}
spring.data.mongodb.database.min-pool-size: 0
spring.data.mongodb.database.max-pool-size: 5
spring.data.mongodb.database.max-connection-idle-time: 3000
spring.data.mongodb.database.max-connection-life-time: 3000

opa.url: ${OPA_URL:http://localhost:8181/v1/data/wks/authz/allow}
keycloak.url: ${KEYCLOAK_URL:http://localhost:8082}

management.health.mongo.enabled: false
management.health.reds.enabled: false
management.endpoints.web.exposure.include: health,info 
management.endpoint.health.show-details: never

case.engine.case-creation-process: case-instance-create