server:
   port: 7101

logging:
   level:
      root: INFO
      
spring.mvc.converters.preferred-json-mapper: gson

spring.data.mongodb.uri: ${MONGO_CONN:mongodb://localhost}
spring.data.mongodb.database: ${MONGO_SHARED_DATABASE:shared}
spring.data.mongodb.database.tenant: ${MONGO_DATABASE:localhost}

mongo.data.import.enabled: true
mongo.data.import.folder: ${IMPORT_DIR_PATH:./data}/mongodb

keycloak.data.import.enabled: true
keycloak.data.import.url: ${KEYCLOAK_URL:http://localhost:8082}
keycloak.data.import.admin: ${KEYCLOAK_ADMIN:admin}
keycloak.data.import.adminpass: ${KEYCLOAK_PASS:admin}
keycloak.data.import.portal-clientid: wks-portal
keycloak.data.import.externaltasks-clientid: wks-external-tasks
keycloak.data.import.externaltasks-secret: ${KEYCLOAK_EXTERNALTASKS_SECRET:replaceme}
keycloak.data.import.emailtocase-clientid: wks-email-to-case
keycloak.data.import.emailtocase-secret: ${KEYCLOAK_EMAILTOCASE_SECRET:replaceme}
keycloak.data.import.realm: ${spring.data.mongodb.database.tenant}
keycloak.data.import.dns: localhost
keycloak.data.import.port: :3001
keycloak.data.import.protocol: http://
keycloak.data.import.redirecturl: ${keycloak.data.import.protocol}${keycloak.data.import.dns}${keycloak.data.import.port}/*
keycloak.data.import.weborigins: ${keycloak.data.import.protocol}${keycloak.data.import.dns}${keycloak.data.import.port}
keycloak.data.import.username: ${KEYCLOAK_DEFAULT_USER:demo}
keycloak.data.import.password: ${KEYCLOAK_DEFAULT_USER_PASSWORD:demo}
keycloak.data.import.firstname: ${KEYCLOAK_DEFAULT_USER_FIRST_NAME:demo}
keycloak.data.import.lastname: ${KEYCLOAK_DEFAULT_USER_LAST_NAME:demo}
keycloak.data.import.email: ${KEYCLOAK_DEFAULT_USER_EMAIL:demo@demo.com}

camunda7.data.import.enabled: ${CAMUNDA7_DATA_IMPORT_ENABLED:true}
camunda7.data.import.url: ${CAMUNDA_URL:http://localhost:8080/engine-rest}
camunda7.data.import.folder: ${IMPORT_DIR_PATH:./data}/camunda7
camunda7.data.import.tenant: ${spring.data.mongodb.database.tenant}

camunda8.data.import.enabled: ${CAMUNDA8_DATA_IMPORT_ENABLED:false}
camunda8.data.import.folder: ${IMPORT_DIR_PATH:data}/camunda8
zeebe.client.broker.gateway-address: ${CAMUNDA8_ZEEBE_GATEWAY_ADDRESS:127.0.0.1:26500}
zeebe.client.security.plaintext: true