name: tags

on:
  push:
    tags:
      - '**'

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: wkspower
  KEYCLOAK_URL: http://localhost:8082
  WKS_API_URL: http://localhost:8081
  WKS_EMAIL_API_URL: http://localhost:8083
  WKS_STORAGE_API_URL: http://localhost:8085
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
        
    - name: Extract tag name
      id: extract_tag
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"

    - name: Set up jdk 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Set up maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build all for backend api
      run: mvn -B package --file apps/java/pom.xml

    - name: Install dependencies for case-portal
      run: yarn --cwd apps/react/case-portal install

    - name: Set Node.js Heap Size
      run: export NODE_OPTIONS="--max-old-space-size=4096"      

    - name: Build for case-portal
      run: REACT_APP_KEYCLOAK_URL=${{ env.KEYCLOAK_URL }} REACT_APP_API_URL=${{ env.WKS_API_URL }} REACT_APP_EMAIL_URL=${{ env.WKS_EMAIL_API_URL }} REACT_APP_STORAGE_URL=${{ env.WKS_STORAGE_API_URL }} yarn --cwd apps/react/case-portal build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image for storage-api
      uses: docker/build-push-action@v2
      with:
        context: ./storage-api
        platforms: linux/amd64,linux/arm64
        file: storage-api/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/storage-api:${{ steps.extract_tag.outputs.tag }}"

    - name: Build and push Docker image for opa
      uses: docker/build-push-action@v2
      with:
        context: ./opa
        platforms: linux/amd64,linux/arm64
        file: opa/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/opa:${{ steps.extract_tag.outputs.tag }}"

    - name: Build and push Docker image for bpm-engine-c7-external-service
      uses: docker/build-push-action@v2
      with:
        context: ./bpm-engine-c7-external-service
        platforms: linux/amd64,linux/arm64
        file: bpm-engine-c7-external-service/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/bpm-engine-c7-external-service:${{ steps.extract_tag.outputs.tag }}"

    - name: Build and push Docker image for case-engine-rest-api
      uses: docker/build-push-action@v2
      with:
        context: ./case-engine-rest-api
        platforms: linux/amd64,linux/arm64
        file: case-engine-rest-api/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/case-engine-rest-api:${{ steps.extract_tag.outputs.tag }}"

    - name: Build and push Docker image for demo-data-loader
      uses: docker/build-push-action@v2
      with:
        context: ./demo-data-loader
        platforms: linux/amd64,linux/arm64
        file: demo-data-loader/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/demo-data-loader:${{ steps.extract_tag.outputs.tag }}"

    - name: Build and push Docker image email-to-case
      uses: docker/build-push-action@v2
      with:
        context: ./email-to-case
        platforms: linux/amd64,linux/arm64
        file: email-to-case/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/email-to-case:${{ steps.extract_tag.outputs.tag }}"

    - name: Build and push Docker image for case-portal
      uses: docker/build-push-action@v2
      with:
        context: ./case-portal
        platforms: linux/amd64,linux/arm64
        file: case-portal/deployments/Dockerfile
        push: true
        tags: "${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/case-portal:${{ steps.extract_tag.outputs.tag }}"
