server:
   port: 8085

logging:
   level:
      root: INFO
      com.wks.api.security: DEBUG
      org.apache.http: DEBUG
            
spring.mvc.converters.preferred-json-mapper: gson

management.health.mongo.enabled: false
management.health.reds.enabled: false
management.endpoints.web.exposure.include: health,info 
management.endpoint.health.show-details: never

opa.url: ${OPA_URL:http://localhost:8181/v1/data/wks/authz/allow}
keycloak.url: ${KEYCLOAK_URL:http://localhost:8082}

# minio
driver.storage.factoryclass: minio
driver.storage.endpoint.url: ${MINIO_HOST:localhost}
driver.storage.endpoint.port: 9000
driver.storage.endpoint.secure: false
driver.storage.endpoint.signing.region: nyc3
driver.storage.endpoint.bucket.prefix: 
driver.storage.accesskey: minio
driver.storage.secretkey: "#minio00#"
driver.storage.uploads.backend.protocol: http
driver.storage.uploads.backend.port: 9000
driver.storage.uploads.backend.url: localhost
driver.storage.uploads.file.min.size:  1024
driver.storage.uploads.file.max.size:  20000000

# digital ocean
# driver.storage.factoryclass: do
# driver.storage.endpoint.url: nyc3.digitaloceanspaces.com
# driver.storage.endpoint.port: 443
# driver.storage.endpoint.secure: true
# driver.storage.endpoint.signing.region: nyc3
# driver.storage.endpoint.bucket.prefix: wks 
# driver.storage.accesskey: <accesskey>
# driver.storage.secretkey: <secretkey>
# driver.storage.uploads.backend.protocol: https
# driver.storage.uploads.backend.port: -1
# driver.storage.uploads.backend.url: nyc3.digitaloceanspaces.com
# driver.storage.uploads.file.min.size:  1024
# driver.storage.uploads.file.max.size:  20000000
